    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.fpui;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

/**
 *
 * @author fprotect
 */
public class fpUI extends javax.swing.JFrame {
    
    Properties props;
    
    fpuiEngine fp;
    
    Process pPreProc;
    Process pPrimFilter;
    Process pSecFilter;
    Process pStreamSink;
    
    /**
     * Creates new form fpuiFrameMain
     */
    public fpUI() throws IOException {
        initComponents();
        
        buttonStop.setEnabled(false);
        
        fpuiOutLogger outPrim = new fpuiOutLogger(textOutPrim);
        fpuiOutLogger outSec = new fpuiOutLogger(textOutSec);
        fpuiOutLogger log = new fpuiOutLogger(textLog);
        fpuiOutLogger stats = new fpuiOutLogger(textOutStats);
        fpuiOutLogger[] outs = new fpuiOutLogger[]{outPrim, outSec, log, stats};
        
        props = new Properties();
        InputStream in = this.getClass().getResourceAsStream("/FProtect.properties");
        props.load(in);
        
        File propsFile = new File("FProtect.properties");
        if(propsFile.isFile())
        {
            in = new FileInputStream(propsFile);
            props.load(in);
        }
        else
            props.store(new FileOutputStream("FProtect.properties"), null);
        
        fp = new fpuiEngine(props, outs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupModels = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelTextArea = new javax.swing.JScrollPane();
        textOutSec = new javax.swing.JTextArea();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textOutStats = new javax.swing.JTextArea();
        buttonEval = new javax.swing.JButton();
        panelTextArea2 = new javax.swing.JScrollPane();
        textOutPrim = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioButtonModelRf = new javax.swing.JRadioButton();
        radioButtonModelGbt = new javax.swing.JRadioButton();
        radioButtonModelLr = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FProtect");
        setName("frameMain"); // NOI18N

        textOutSec.setEditable(false);
        textOutSec.setBackground(new java.awt.Color(255, 255, 255));
        textOutSec.setColumns(20);
        textOutSec.setLineWrap(true);
        textOutSec.setRows(5);
        panelTextArea.setViewportView(textOutSec);

        buttonStart.setText("Start");
        buttonStart.setName("buttonStart"); // NOI18N
        buttonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStartMouseClicked(evt);
            }
        });

        buttonStop.setText("Stop");
        buttonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStopMouseClicked(evt);
            }
        });

        textLog.setEditable(false);
        textLog.setColumns(20);
        textLog.setRows(5);
        jScrollPane1.setViewportView(textLog);

        textOutStats.setColumns(20);
        textOutStats.setRows(5);
        jScrollPane2.setViewportView(textOutStats);

        buttonEval.setText("Generate Stats");
        buttonEval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEvalMouseClicked(evt);
            }
        });

        textOutPrim.setEditable(false);
        textOutPrim.setBackground(new java.awt.Color(255, 255, 255));
        textOutPrim.setColumns(20);
        textOutPrim.setLineWrap(true);
        textOutPrim.setRows(5);
        panelTextArea2.setViewportView(textOutPrim);

        jLabel1.setText("Output (Primary):");

        jLabel2.setText("Output (Secondary):");

        jLabel3.setText("Log:");

        jLabel4.setText("Classification model:");

        buttonGroupModels.add(radioButtonModelRf);
        radioButtonModelRf.setSelected(true);
        radioButtonModelRf.setText("Random Forest");

        buttonGroupModels.add(radioButtonModelGbt);
        radioButtonModelGbt.setText("Gradient Boosted Tree");
        radioButtonModelGbt.setToolTipText("");

        buttonGroupModels.add(radioButtonModelLr);
        radioButtonModelLr.setText("Logistic Regression");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonEval, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 64, Short.MAX_VALUE))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                                        .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(radioButtonModelGbt)
                                            .addComponent(radioButtonModelRf)
                                            .addComponent(radioButtonModelLr))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(panelTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonModelRf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonModelGbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonModelLr)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(buttonEval, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(panelTextArea2)
                    .addComponent(panelTextArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStartMouseClicked
        try {
            buttonStart.setEnabled(false);
            buttonStop.setEnabled(true);
            String model = "";
            if(radioButtonModelRf.isSelected())
                model = "RANDOM_FOREST";
            else if(radioButtonModelGbt.isSelected())
                model = "GBT";
            else if(radioButtonModelLr.isSelected())
                model = "LOGISTIC_REGRESSION";
            fp.setClassifier(model);
            fp.start();
        } catch (IOException ex) {
            Logger.getLogger(fpUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonStartMouseClicked

    private void buttonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStopMouseClicked
        try {
            buttonStart.setEnabled(true);
            buttonStop.setEnabled(false);
            fp.stop();
        } catch (InterruptedException ex) {
            Logger.getLogger(fpUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonStopMouseClicked

    private void buttonEvalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEvalMouseClicked
        try {
            fp.eval();
        } catch (IOException ex) {
            Logger.getLogger(fpUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(fpUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonEvalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fpUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(fpUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEval;
    private javax.swing.ButtonGroup buttonGroupModels;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane panelTextArea;
    private javax.swing.JScrollPane panelTextArea2;
    private javax.swing.JRadioButton radioButtonModelGbt;
    private javax.swing.JRadioButton radioButtonModelLr;
    private javax.swing.JRadioButton radioButtonModelRf;
    private javax.swing.JTextArea textLog;
    private javax.swing.JTextArea textOutPrim;
    private javax.swing.JTextArea textOutSec;
    private javax.swing.JTextArea textOutStats;
    // End of variables declaration//GEN-END:variables
}
